### ISSUE TITLE
Compiling using just the word: tds

### ISSUE THREAD

**Issue by JuanmaCopia** [JuanmaCopia/tds18-compiler#15]
we need to create a script to compile the source code (.tds) so that we just type:
    tds myprogram.tds
and the compiling process begins.

**Comment by santiago-m** [comment]
Done! I created a new script named "tds", so in it we can call not only the parser but any other script we could need in the future (like create_intermediate_code for example).-
Commit:
9112780da5c33bbce04c532b094e31ad29e068a8

**Comment by JuanmaCopia** [comment]
Great!
